You just got hired as the first and only data practitioner at a small business experiencing exponential growth. The company needs more structured processes, guidelines, and standards. Your first mission is to structure the human resources data. The data is currently scattered across teams and files and comes in various formats: Excel files, CSVs, JSON files...

You'll work with the following data in the `datasets` folder:
- __Office addresses__
    - Saved in `office_addresses.csv`. 
    - If the value for office is `NaN`, then the employee is remote.
- __Employee addresses__
    - Saved on the first tab of `employee_information.xlsx`.
- __Employee emergency contacts__ 
    - Saved on the second tab of `employee_information.xlsx`; this tab is called `emergency_contacts`. 
    - However, this sheet was edited at some point, and ***the headers were removed***! The HR manager let you know that they should be: `employee_id`, `last_name`, `first_name`, `emergency_contact`, `emergency_contact_number`, and `relationship`.
- __Employee roles, teams, and salaries__ 
    - This information has been exported from the company's human resources management system into a JSON file titled `employee_roles.json`. Here are the first few lines of that file:
```
{"A2R5H9":
  {
    "title": "CEO",
    "monthly_salary": "$4500",
    "team": "Leadership"
  },
 ...
}
```

Read in, merge, and clean the four datasets to make a single combined pandas DataFrame.

- Create a single pandas DataFrame called `employees_final` containing:
    - Index: `employee_id`.
    - Columns: Ensure the DataFrame contains only the following columns, **in the exact order listed**: `employee_first_name`, `employee_last_name`, `employee_country`, `employee_city`, `employee_street`, `employee_street_number`, `emergency_contact`, `emergency_contact_number`, `relationship`, `monthly_salary`, `team`, `title`, `office`, `office_country`, `office_city`, `office_street`, `office_street_number`.
    - Assign employees to offices **based on their country**. For any columns that begin with `office`, replace missing data with `"Remote"`.

In [8]:
import pandas as pd
# Start coding here... 

offices = pd.read_csv("datasets/office_addresses.csv")
offices.head()

          office office_country  ...   office_street office_street_number
0  Leuven Office             BE  ...  Martelarenlaan                   38
1     ESB Office             US  ...    Fifth Avenue                  350
2  WeWork Office             GB  ...      Old Street                  207

[3 rows x 5 columns]

In [9]:
addresses = pd.read_excel("datasets/employee_information.xlsx")
addresses.head()

  employee_id employee_last_name  ...      employee_street employee_street_number
0      A2R5H9             Hunman  ...          Grote Markt                      9
1      H8K0L6               Siff  ...         Baker Street                    221
2      G4R7V0              Sagal  ...         Perry Street                     66
3      M1Z7U9             Coates  ...  Rue de l'Université                      7

[4 rows x 7 columns]

In [10]:
emergency_contacts_header = ["employee_id", "last_name", "first_name",
                             "emergency_contact", "emergency_contact_number", "relationship"]


emergency_contacts = pd.read_excel("datasets/employee_information.xlsx", 
                                   sheet_name="emergency_contacts", 
                                   header=None,
                                   names=emergency_contacts_header)

emergency_contacts.head()

  employee_id last_name  ... emergency_contact_number relationship
0      A2R5H9    Hunman  ...          +32-456-5556-84      Brother
1      H8K0L6      Siff  ...         +44-020-5554-333       Sister
2      G4R7V0     Sagal  ...           +1-202-555-194      Husband
3      M1Z7U9    Coates  ...          +1-202-555-0130         Wife

[4 rows x 6 columns]

In [11]:
roles = pd.read_json("datasets/employee_roles.json", orient="index")
roles.head()

                     title monthly_salary               team
A2R5H9                 CEO          $4500         Leadership
H8K0L6                 CFO          $4500         Leadership
G4R7V0  Business Developer          $3000              Sales
M1Z7U9      Office Manager          $2000  People Operations

In [14]:
employees = addresses.merge(offices, left_on="employee_country", right_on="office_country", how="left")
employees = employees.merge(roles, left_on="employee_id", right_on=roles.index)
employees = employees.merge(emergency_contacts, on="employee_id")

employees.head()

  employee_id employee_last_name  ... emergency_contact_number relationship
0      A2R5H9             Hunman  ...          +32-456-5556-84      Brother
1      H8K0L6               Siff  ...         +44-020-5554-333       Sister
2      G4R7V0              Sagal  ...           +1-202-555-194      Husband
3      M1Z7U9             Coates  ...          +1-202-555-0130         Wife

[4 rows x 20 columns]

In [15]:
for col in ["office", "office_country", "office_city", "office_street", "office_street_number"]:
    employees[col].fillna("Remote", inplace=True)

final_columns = ["employee_id", "employee_first_name", "employee_last_name", "employee_country", 
                 "employee_city", "employee_street", "employee_street_number", 
                 "emergency_contact", "emergency_contact_number", "relationship", 
                 "monthly_salary", "team", "title", "office", "office_country", 
                 "office_city", "office_street", "office_street_number"]

employees_final = employees[final_columns]
employees_final.set_index("employee_id", inplace=True)

employees_final.head()

            employee_first_name  ... office_street_number
employee_id                      ...
A2R5H9                      Jax  ...                 38.0
H8K0L6                     Tara  ...                207.0
G4R7V0                    Gemma  ...                350.0
M1Z7U9                      Tig  ...               Remote

[4 rows x 17 columns]